media/i2c: tc358743: Fix build fail with error unused function 'tc358743_get_mbus_config' on Android 14
error log:
  error: unused function 'tc358743_get_mbus_config' [-Werror,-Wunused-function]