Revert "MA-19289-1 GKI: v4l2-subdev: Remove obsolete g/s_parm"
For fix build fail on Android 14.
error log:
  error: field designator 'g_parm' does not refer to any field in type 'const struct v4l2_subdev_video_ops'
  error: field designator 's_parm' does not refer to any field in type 'const struct v4l2_subdev_video_ops'

This reverts commit e0bc859c3672f81abe7a80b851e2ea30771b67d0.