ARM64: configs: Fix missing config build error on Android 15
Enable below missing configs in menuconfig.
Then regenerate by savedefconfig.

error log:
ERROR: files are incompatible: Runtime info and framework compatibility matrix
       are incompatible: No compatible kernel requirement found
       (kernel FCM version = 202404).
For kernel requirements at matrix level 202404, Kernel config errors:
    Missing config CONFIG_DM_DEFAULT_KEY
    Missing config CONFIG_DM_SNAPSHOT
    Missing config CONFIG_DM_VERITY
    Missing config CONFIG_IP_NF_TARGET_REDIRECT
    For config CONFIG_NETFILTER_XT_MATCH_COMMENT, value = m but required y