media: tevs: fix compilation error for linux 6.12
1. 'v4l2_subdev_get_try_format' is deprecated in linux 6.12
   Refer bc0e8d91 commit:
     'bc0e8d91 media: v4l: subdev: Switch to stream-aware state functions'

   Build error log:
     error: implicit declaration of function ‘v4l2_subdev_get_try_format’

2. [gs]_frame_interval into pad operations
   API change according with 287fe16083 commit:
     '287fe16083 media: v4l2-subdev: Turn .[gs]_frame_interval into pad operations'

   Build error log:
     error: ‘const struct v4l2_subdev_video_ops’ has no member named ‘g_frame_interval’
     error: ‘const struct v4l2_subdev_video_ops’ has no member named ‘s_frame_interval’