media: v4l2: capture: fix issue that camera sometimes can't be initialized properly
-------------------------------------------------------------------------------------------------
gst-launch-1.0 imxv4l2src device=/dev/video1 ! imxv4l2sink
ov5645_mipi 3-003c: Please assign pixel format, width and height
====== IMXV4L2SRC: 4.4.5 build on Jun 27 2019 07:23:14. ======
====== IMXV4L2SINK: 4.4.5 build on Jun 27 2019 07:23:13. ======
ov5645_mipi 3-003c: Please assign pixel format, width and height
Setting pipeline to PAUSED ...
display(/dev/fb0) resolution is (800x480).
Pipeline is live and does not need PREROLL ...
Setting pipeline to PLAYING ...
New clock: GstSystemClock
ov5645_mipi 3-003c: s_stream: 1
v4l2sink need allocate 3 buffers.
ERROR: from element /GstPipeline:ov5645_mipi 3-003c: s_stream: 0
pipeline0/GstImxV4l2Src:imxv4l2src0: Internal data stream error.
Additional debug info:
../../../../git/libs/gst/base/gstbasesrc.c(3055): gst_base_src_loop (): /GstPipeline:pipeline0/GstImxV4l2Src:imxv4l2src0:
streaming stopped, reason error (-5)
-------------------------------------------------------------------------------------------------