ARM64: configs: Fix missing config build error
Enable below missing configs in menuconfig, then regenerate by savedefconfig.

error log:
ERROR: files are incompatible: Runtime info and framework compatibility matrix are incompatible: No compatible kernel requirement found (kernel FCM version = 8).
For kernel requirements at matrix level 8, Kernel config errors:
    Missing config CONFIG_DM_DEFAULT_KEY
    Missing config CONFIG_DM_SNAPSHOT
    Missing config CONFIG_DM_VERITY
    Missing config CONFIG_FUSE_FS
    For config CONFIG_IP_NF_TARGET_REDIRECT, value = m but required y
    Missing config CONFIG_MD
    Missing config CONFIG_USB_CONFIGFS_F_FS