ARM: pico-imx6: port pico-imx6 from v4.9.88 Signed-off-by: Po Cheng <po.cheng@technexion.com>
**************************************************
Squashed commit of the following:

commit c62292d8d137b9523145963f76bd46ad59afbba0
Author: Richard Hu <richard.hu@technexion.com>
Date:   Mon Oct 8 13:43:36 2018 +0800

    ARM: dts: pico-imx6-qca: add support for Hobbit baseboard

commit 1ddf6a912811cbce476f55e4c1c4f73ad1f761ac
Author: Richard Hu <richard.hu@technexion.com>
Date:   Mon Oct 8 13:40:08 2018 +0800

    ARM: dts: pico-imx6-qca: add support for Dwarf baseboard

commit 7f45f874fa81954a7bfe55fafc2f7304492ece98
Author: Richard Hu <richard.hu@technexion.com>
Date:   Tue Sep 25 15:59:47 2018 +0800

    ARM: dts: pico-imx6-qca: add support for Nymph baseboard

commit c6a67baebb9417639fd83520e1c9528fd8e10f26
Author: alvin.chen <alvin.chen@technexion.com>
Date:   Fri Jan 18 17:30:26 2019 +0800

    baseboard_pico_pi: Add BOSCH BMP388 chip support for PICO-PI

commit 9383220f791c4ee2c6431eae3dbe6a39f4cb67a8
Author: Ray Chang <ray.chang@technexion.com>
Date:   Tue Dec 25 15:13:18 2018 +0800

    ARM: dtsi: baseboard_pico_pi: default baseboard set to rev.B1

commit 61f2e8381009ea02efccf53f60855a4cccf1ca47
Author: alvin.chen <alvin.chen@technexion.com>
Date:   Mon Dec 24 13:51:16 2018 +0800

    baseboard_pico_pi: Add BOSCH BNO055 chip support for PICO-PI

commit 567339e1b2995b11a58ea7ef125dc9626a5d1654
Author: alvin.chen <alvin.chen@technexion.com>
Date:   Fri Dec 21 17:50:38 2018 +0800

    baseboard_pico_pi: Add BOSCH bme680 chip support for PICO-PI

commit bf7923ae9bd6498bf0cc9d62ec1c7e946a2b1d6d
Author: Ray Chang <ray.chang@technexion.com>
Date:   Thu Oct 25 09:46:06 2018 +0800

    ARM: dtsi: baseboard_pico_dwarf: add DS1337 RTC to I2C3 bus in Dwarf

commit b6c009532d0efdae950b6741cd924ce4c6294e23
Author: Richard Hu <richard.hu@technexion.com>
Date:   Tue Oct 23 13:13:06 2018 +0800

    ARM: dtsi: baseboard_pico_nymph: correct DS1337 RTC from I2C3 to I2C1 bus

    For Nymph rev.A1, it moves DS1337 RTC chip from I2C3 to I2C1 bus.

commit d6977c3291adbf96cfd10f9c7ffff8be4434932d
Author: alvin.chen <alvin.chen@technexion.com>
Date:   Mon Aug 27 14:01:26 2018 +0800

    baseboard_pico_pi: add qca9377 wifi power switch function.

commit 187355a4a46dd49bb27cd7da1533fe9ca652962e
Author: Richard Hu <richard.hu@technexion.com>
Date:   Thu Jan 31 11:15:14 2019 +0800

    ARM: dtsi: pico-imx6: extend memory region from 1GB to 2GB to support PICO-IMX6Q with 2GB DDR3L

commit a577117faf480bb22bf04d41b01e89132ee8b7e9
Author: Richard Hu <richard.hu@technexion.com>
Date:   Thu Nov 22 15:17:08 2018 +0800

    ARM: dtsi: pico-imx6: suppress flicking on LVDS panel for pico-imx6s/dl

    Set parent clock of LDB as PLL2_PFD0_352M to increase LDB output frequency from 198MHz to 352MHz.

commit 6b7bbed9c47a086a73926280152008b29dca5d4e
Author: Richard Hu <richard.hu@technexion.com>
Date:   Tue Nov 20 13:53:07 2018 +0800

    ARM: dtsi: pico-imx6: increase PWM frequency to 20k Hz to avoid flicking

commit 6f818927ac4bcc561db8b5dc84e086af7e5e9a3b
Author: Ray Chang <ray.chang@technexion.com>
Date:   Mon Nov 19 15:29:09 2018 +0800

    ARM: dtsi: pico-imx6-qca: change to use rfkill for Bluetooth control

commit c3999eccdaa0dc32c4e92a2d0d6607f83fc6cd1b
Author: Richard Hu <richard.hu@technexion.com>
Date:   Thu Nov 8 10:41:25 2018 +0800

    ARM: dtsi: pico-imx6: add missing IOMUX settings for BT

commit 4104ce8b3aaa65f528a75808fb34e8c2714c49cd
Author: Richard Hu <richard.hu@technexion.com>
Date:   Fri Oct 19 15:36:49 2018 +0800

    ARM: dtsi: pico-imx6: enable 32KHz clock output for BRCM WIFI/BT anyway

commit 1c663c02c73b65b86ce253beb663c99e039f1f9e
Author: Richard Hu <richard.hu@technexion.com>
Date:   Fri Oct 5 17:05:58 2018 +0800

    ARM: dtsi: pico-imx6-qca: correct framebuffer BPP to fit in the bpp settings of gst-player in Yocto

commit b9bf9059d604ff061086e81f1ac08b6ba00474d5
Author: Richard Hu <richard.hu@technexion.com>
Date:   Mon Oct 1 11:38:50 2018 +0800

    ARM: dtsi: pico-imx6: correct framebuffer BPP to fit in the bpp settings of gst-player in Yocto

commit b169856bba5df80c67b0e10e5e75e8bc05acb1a1
Author: Richard Hu <richard.hu@technexion.com>
Date:   Tue Sep 25 16:01:34 2018 +0800

    ARM: dts: pico-imx6-qca: change model name for pi baseboard

commit e6f8079ec033ea1a057009fe56808b2da292302c
Author: Richard Hu <richard.hu@technexion.com>
Date:   Mon Sep 17 18:02:08 2018 +0800

    ARM: dtsi: pico-imx6: add QCA9377-3 support for PICO-IMX6 rev.B1

commit ead894348a4e9b594732af8fe061eb6de89df468
Author: Richard Hu <richard.hu@technexion.com>
Date:   Fri Jan 5 11:20:07 2018 +0800

    ARM: dts: add support for TechNexion PICO-IMX6 boards

    Add dts for TechNexion PICO-IMX6_DWARF, PICO-IMX6_HOBBIT, PICO-IMX6_NYMPH,
    and PICO-IMX6_PI boards.

commit a5602176365042e5dcbfa642e81ae1bcae9107be
Author: Richard Hu <richard.hu@technexion.com>
Date:   Thu Jan 4 18:41:31 2018 +0800

    ARM: dts: add support for TechNexion PICO-IMX6 SOM

    Add dtsi for TechNexion PICO-IMX6 CPU module.

commit c12a56b5b824be6a9f4bbb9efd507e2ec945f749
Author: Richard Hu <richard.hu@technexion.com>
Date:   Wed Dec 20 11:12:47 2017 +0800

    ARM: dts: add support for TechNexion PICO baseboards

    Add TechNexion PICO-DWARF, PICO-HOBBIT, PICO-NYMPH and PICO-PI baseboards.

commit 81d8a729ae3d504b36824a408c371fdd0e3a3748
Author: Wig C <wig.cheng@technexion.com>
Date:   Thu Apr 14 18:54:19 2016 +0800

    ARM: dts: imx6: pinfunc: add pin definition of XTALOSC_REF_CLK_32K

commit 2d87e3fbc126cf9af1f8f942a3c664d0847d09cd
Author: Tapani Utriainen <tapani@technexion.com>
Date:   Thu May 19 18:12:04 2016 +0800

    technexion: add macros for GPIO / interrupt definitions

    Using the macros in this file allows us to define a gpio once, and be able
    to define them as interrupts in the baseboard files without duplicating the
    definitions.

commit 769cc6044937e8477f9654acc9652b6967f72491
Author: alvin.chen <alvin.chen@technexion.com>
Date:   Fri Jan 18 17:31:14 2019 +0800

    ARM: configs: tn_imx_defconfig: add bmp388 driver support

commit bbc930dbeaedb6ad5dba456dc5742e5921d3641a
Author: alvin.chen <alvin.chen@technexion.com>
Date:   Mon Dec 24 13:49:57 2018 +0800

    ARM: configs: tn_imx_defconfig: add driver support for BNO055

commit 7df96e0f99b44b7cdc9984137179599e455d6bca
Author: alvin.chen <alvin.chen@technexion.com>
Date:   Fri Dec 21 17:54:04 2018 +0800

    ARM: configs: tn_imx_defconfig: add bme680 driver support

commit e41a2ce69344aa2031c60d9f8bec8ab698b5aa1c
Author: Ray Chang <ray.chang@technexion.com>
Date:   Fri Nov 30 11:20:44 2018 +0800

    ARM: tn_imx_defconfig: enable CONFIG_ATH10K_PCI for QCA wifi PCIe modules

commit 365c40a890191ad299b5a42b8f428dae22633e5a
Author: Ray Chang <ray.chang@technexion.com>
Date:   Mon Nov 19 15:22:56 2018 +0800

    ARM: tn_imx_defconfig: enable 'CONFIG_RFKILL_GPIO' for QCA modules

commit 6965e5258b3d402250cac1a7058e9b76543ea710
Author: Richard Hu <richard.hu@technexion.com>
Date:   Thu Oct 25 13:09:01 2018 +0800

    ARM: tn_imx_defconfig: enable CONFIG_VIDEO_MXC_CSI_CAMERA_LEGACY

    i.mx7 uses mx6s_capture_legacy.c as camera capture driver

commit 0a5f32171083eb3bb342ee315dec0cd347358711
Author: Richard Hu <richard.hu@technexion.com>
Date:   Tue Oct 16 13:54:37 2018 +0800

    ARM: tn_imx_defconfig: enable 'CONFIG_BCMDHD_SDIO' for NXP bcmdhd v1.141

commit b9194c7b1b9430c5cb70a71f047121249d19cf6c
Author: Richard Hu <richard.hu@technexion.com>
Date:   Fri Sep 21 13:47:54 2018 +0800

    ARM: tn_imx_defconfig: enable bcmdhd wifi driver to support AP6335(BCM4339) and AP6212(BCM43438) wifi(SDIO) modules

commit 442096b5f070f4b345dd6055b71ea491a3ff46e9
Author: Richard Hu <richard.hu@technexion.com>
Date:   Thu Sep 20 14:14:07 2018 +0800

    ARM: tn_imx_defconfig: enable ov5645 mipi-csi2 camera driver for i.mx6Q/D/DL/S

commit 303c463c0377cff8d75421446d318d409ab2c810
Author: Richard Hu <richard.hu@technexion.com>
Date:   Wed Aug 8 14:35:01 2018 +0800

    ARM: configs: tn_imx_defconfig: update local version to 2.0.0

commit fe9ec8449ed3aceaaf3951e0ffd1ac8cdd5a78d5
Author: Ray Chang <ray.chang@technexion.com>
Date:   Wed Aug 8 10:48:58 2018 +0800

    ARM: configs: tn_imx_defconfig: add qcacld-2.0 driver support

commit b815dd680d48b9aed93faa6a62d7ae256eda1a3a
Author: Tapani Utriainen <tapani@technexion.com>
Date:   Fri Jun 1 18:52:51 2018 +0800

    ARM: tn_imx_defconfig: enable ARM PCSI for iMX6/6UL/7

commit 6bb6785bc141243e900e99d6d365ce91ee508ce9
Author: Richard Hu <richard.hu@technexion.com>
Date:   Thu Jan 4 10:30:51 2018 +0800

    ARM: tn_imx_defconfig: enable ov5645 mipi-csi2 camera support

commit 3015c991c77924eabbdbaabc2148daa6c98ff2b3
Author: Richard Hu <richard.hu@technexion.com>
Date:   Tue Mar 14 10:35:04 2017 +0800

    ARM: tn_imx_defconfig: configure mx6s_capture as module to ensure it's initialized after CSI/PxP driver. Or it may not be initialized properly.

    The error message is as below:

    root@pico-imx7:/unit_tests# gst-launch-1.0 imxv4l2src device=/dev/video1 ! imxv4l2sink
    Please assign pixel format, width and height.
    ====== IMXV4L2SRC: 4.0.9 build on Feb 21 2017 19:01:41. ======
    pxp_lib.c:55 open file error.
    ====== IMXV4L2SINK: 4.0.9 build on Feb 21 2017 19:01:41. ======
    Setting pipeline to PAUSED ...
    ERROR: Pipeline doesn't want to pause.
    Setting pipeline to NULL ...
    Freeing pipeline ...

commit 721b9d0b7481fa1eab0aa90b8d97c95fa75f0305
Author: Richard Hu <richard.hu@technexion.com>
Date:   Wed Jan 3 14:23:08 2018 +0800

    ARM: tn_imx_defconfig: enable bcm43xx rfkill support

commit 53225f0e634e5928cc1865ae8d7c44393b317d9c
Author: Richard Hu <richard.hu@technexion.com>
Date:   Wed Jan 3 13:03:42 2018 +0800

    ARM: tn_imx_defconfig: specify local version

commit 28d1b99002b7f2a92fe8e9885a7b8aeb03340ecb
Author: Tapani Utriainen <tapani@technexion.com>
Date:   Thu May 26 14:12:05 2016 +0800

    ARM: tn_imx_defconfig: disable a few config options (VLAN, userspace FS, ...)

commit 556a4208d049d87387ca19f358b7154eacafcd50
Author: Tapani Utriainen <tapani@technexion.com>
Date:   Wed May 25 17:14:14 2016 +0800

    ARM: tn_imx_defconfig: slim the default config a little further

commit 714db875ea9ca5d74b11c5f4a5b3538dba725760
Author: Tapani Utriainen <tapani@technexion.com>
Date:   Tue May 24 19:45:14 2016 +0800

    ARM: tn_imx_defconfig: cull away some unneccesary drivers from config

commit 6caceea99030fada070dd754032f7d93cc6eb9c3
Author: Richard Hu <richard.hu@technexion.com>
Date:   Fri Dec 29 17:46:37 2017 +0800

    ARM: tn_imx_defconfig: add USB serial support

commit c7409dafebeb8ea038c1afda0a728b588d47fe6d
Author: Richard Hu <richard.hu@technexion.com>
Date:   Fri Dec 29 17:34:50 2017 +0800

    ARM: tn_imx_defconfig: enable FT5x06 touch panel support

commit 1e9a4768da9b1bb326bb4f9e4e48bf958d526ab7
Author: Richard Hu <richard.hu@technexion.com>
Date:   Fri Dec 29 17:22:10 2017 +0800

    ARM: tn_imx_defconfig: enable PWM driven LED support

commit 5878e80b0db06bb07893a06c499e5712405ca4af
Author: Richard Hu <richard.hu@technexion.com>
Date:   Fri Dec 29 16:56:28 2017 +0800

    ARM: tn_imx_defconfig: enable multi-touch support

commit 0e16de5ac548e947bd1362ff2992745a13ef3852
Author: Richard Hu <richard.hu@technexion.com>
Date:   Fri Dec 29 13:23:18 2017 +0800

    ARM: tn_imx_defconfig: build bcmdhd driver as module by default

commit bc98ecae0c9152e713989782f98206b3274f22cd
Author: Richard Hu <richard.hu@technexion.com>
Date:   Tue Dec 26 14:36:31 2017 +0800

    ARM: tn_imx_defconfig: add PCIE support for NXP i.mx series

commit e6f703efc600187d0a24ea19de4d2e39a8bc6d5c
Author: Richard Hu <richard.hu@technexion.com>
Date:   Wed Dec 20 14:59:43 2017 +0800

    ARM: tn_imx_defconfig: enable route and NAT

commit 92d9e53cb1c0667e6071029a67472f4f06eacbfa
Author: Richard Hu <richard.hu@technexion.com>
Date:   Wed Dec 20 13:46:23 2017 +0800

    ARM: tn_imx_defconfig: enable custom GPIO driver for TechNexion boards

    Enable this driver to export and set default status of GPIO on TechNexion boards.

commit a610d2d6e9147738b82a01335140256f2ad2fe4f
Author: Richard Hu <richard.hu@technexion.com>
Date:   Mon Dec 18 11:50:15 2017 +0800

    ARM: configs: add defconfig for TechNexion i.mx products