sound: imx-wm8960: fix compilation error for linux 6.12
1. 'asoc_rtd_to_cpu' and 'asoc_rtd_to_codec' is deprecated in linxu 6.12

   Build error log:
     error: implicit declaration of function ‘asoc_rtd_to_cpu’
     error: implicit declaration of function ‘asoc_rtd_to_codec’

2. Accroding with below change:
    '0edb555a65d1 platform: Make platform_driver::remove() return void'

   Build error log:
    error: initialization of ‘void (*)(struct platform_device *)’
    from incompatible pointer type ‘int (*)(struct platform_device *)’
    [-Werror=incompatible-pointer-types]