ASoC: fsl-asoc-card: fix compilation error for linux 6.12
API change on linux 6.12
'asoc_rtd_to_codec' is deprecated in linux 6.12

Build error log:
  error: assignment to expression with array type
  error: implicit declaration of function ‘asoc_rtd_to_codec’